[package]
name = "open4x-server"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "open4x-server"
path = "src/main.rs"

[dependencies]
serde       = { workspace = true }
serde_json  = { workspace = true }
ulid        = { workspace = true }
ed25519-dalek = { workspace = true }
rand        = { workspace = true }
open4x-protocol = { path = "../open4x-protocol" }

libciv      = { path = "../libciv" }
libhexgrid  = { path = "../libhexgrid" }
axum        = { version = "0.8", features = ["ws"] }
tokio       = { workspace = true }
dashmap     = { version = "6" }
tower-http  = { version = "0.6", features = ["cors", "fs"] }

[dev-dependencies]
tower           = { version = "0.5", features = ["util"] }
http-body-util  = "0.1"
hex             = "0.4"
